# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'msv.ui'
#
# Created: Sat Aug  1 11:32:33 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.except_but = QtWidgets.QPushButton(self.centralwidget)
        self.except_but.setObjectName("except_but")
        self.verticalLayout_2.addWidget(self.except_but)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.import_but = QtWidgets.QPushButton(self.centralwidget)
        self.import_but.setObjectName("import_but")
        self.verticalLayout_2.addWidget(self.import_but)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.import_but_2 = QtWidgets.QPushButton(self.centralwidget)
        self.import_but_2.setObjectName("import_but_2")
        self.verticalLayout_2.addWidget(self.import_but_2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.check_but = QtWidgets.QPushButton(self.centralwidget)
        self.check_but.setObjectName("check_but")
        self.verticalLayout_2.addWidget(self.check_but)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.tree_page = QtWidgets.QWidget()
        self.tree_page.setObjectName("tree_page")
        self.stackedWidget.addWidget(self.tree_page)
        self.check_page = QtWidgets.QWidget()
        self.check_page.setObjectName("check_page")
        self.stackedWidget.addWidget(self.check_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "层级错误", None, -1))
        self.except_but.setText(QtWidgets.QApplication.translate("MainWindow", "导出所选层级", None, -1))
        self.import_but.setText(QtWidgets.QApplication.translate("MainWindow", "加载old层级", None, -1))
        self.import_but_2.setText(QtWidgets.QApplication.translate("MainWindow", "加载new层级", None, -1))
        self.check_but.setText(QtWidgets.QApplication.translate("MainWindow", "对比所选层级", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "clear", None, -1))

